version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /etc/php/8.2/cli/conf.d/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
    environment:
      - QUEUE_CONNECTION=redis
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=yes
      - XDEBUG_MODE=debug

      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_SCHEME=${MAIL_SCHEME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME} 
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - TZ=${APP_TIMEZONE}
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_01
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/docker/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  # queue:
  #   build: .
  #   container_name: laravel_queue
  #   working_dir: /var/www
  #   depends_on:
  #     - redis
  #     - app
  #   entrypoint: [ "sh", "/var/www/docker/worker.sh" ]

  supervisor:
    build: .
    container_name: laravel_supervisor
    working_dir: /var/www
    depends_on:
      - app
    volumes:
      - .:/var/www
    entrypoint: [ "supervisord", "-c", "/var/www/docker/supervisord.conf" ]
