version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis
    environment:
      - QUEUE_CONNECTION=redis
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=yes
      - XDEBUG_MODE=debug
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_01
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/docker/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  # queue:
  #   build: .
  #   container_name: laravel_queue
  #   working_dir: /var/www
  #   depends_on:
  #     - redis
  #     - app
  #   entrypoint: [ "sh", "/var/www/docker/worker.sh" ]

  supervisor:
    build: .
    container_name: laravel_supervisor
    working_dir: /var/www
    depends_on:
      - app
    volumes:
      - .:/var/www
    entrypoint: [ "supervisord", "-c", "/var/www/docker/supervisord.conf" ]
