services:
  frontend:
    build: .
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
